# Generated by Django 2.2.5 on 2022-03-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcatogory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'um_Subcatogory',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('age', models.CharField(max_length=150)),
                ('mobileNo', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'um_user',
            },
        ),
        migrations.CreateModel(
            name='Catogory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Subcatogory')),
            ],
            options={
                'db_table': 'um_Catogory',
            },
        ),
    ]
